### ISSUE TITLE
broken .nc file

### ISSUE THREAD

**Issue by j0kaso** [arose/mdsrv#12]
DPDP.nc file from examples (attached) is broken or can not be loaded.

Error:
```
http://127.0.0.1:42370/traj/frame/NaN/cwd/data/DPDP.nc        [HTTP/1.0 404 NOT FOUND 15ms]
RangeError: attempting to construct out-of-bounds TypedArray on ArrayBuffer
```
[DPDP.tar.gz](https://github.com/arose/mdsrv/files/564085/DPDP.tar.gz)

**Comment by arose** [comment]
still a problem?

**Comment by j0kaso** [comment]
working! Thanks!
