### ISSUE TITLE
add Versioneer

### ISSUE THREAD

**Issue by arose** [arose/mdsrv#13]
see https://github.com/warner/python-versioneer

also change the DEVELOPMENT.md file to include the following:

## Making a Release

We use Versioneer to automatically update the version string (of a release but also in development). This means for a release a new git tag should be created. The tag should be of the form vX.Y or vX.Y.Z and generally follow pep440 with a prefixed "v".

```
git tag  -a vX.Y -m "version X.Y"
git push
git push origin --tags
python setup.py sdist upload -r pypi  # better use twine for uploading, see below
```

To ensure a secure upload use twine:

```
# Create some distributions in the normal way:
python setup.py sdist
# Upload with twine:
twine upload dist/*
```

**Comment by j0kaso** [comment]
done: https://github.com/arose/mdsrv/commit/ad2c319a6a00cee4c110fe39492370b33e74a7d4
