### ISSUE TITLE
Trajectory interpolation options only work for previously "loaded" trajectory

### ISSUE THREAD

**Issue by j0kaso** [arose/mdsrv#17]
Interpolation Type "spline" and "linear" only work for frames previously run with no interpolation type.
If the trajectory is not run completely and those frames are run again with an interpolation, they stop at the last loaded frame.

**Comment by arose** [comment]
ngl issue, I guess. Have you checked with latest version?

**Comment by j0kaso** [comment]
yes still present with version 0.10.3. will reference the issue.
