### ISSUE TITLE
update to ngl 0.7 when released

### ISSUE THREAD

**Issue by arose** [arose/mdsrv#4]

**Comment by hainm** [comment]
is it possible for you to update before release. I get used to the beautiful render in `NGL`  0.7 in `nglviewer`.

If not, can you point me to where or how to update by myself?

**Comment by arose** [comment]
done, see c2882ea297621b581a1e3c2d8f08e0507d9acaab

**Comment by j0kaso** [comment]
Cool! I'll test everything :-)

Am 05.10.2016 06:57 schrieb "Alexander Rose" notifications@github.com:
