### ISSUE TITLE
need your overview about mdsrv: trying to plug pytraj

### ISSUE THREAD

**Issue by hainm** [arose/mdsrv#6]
Hi,

I am thinking about forking your repo so I can use `mdsrv` with `pytraj`. Using `nglview` with `notebook` is not convenient  for quick visualization. It's a bit slower to start the notebook than `mdsrv`. 

Can you point me to the right direction? just a brief direction so I know where/how to read your code.

**Comment by hainm** [comment]
In this [line](https://github.com/arose/mdsrv/blob/master/mdsrv/mdsrv.py#L255), does that mean trajectory file is open every time `mdsrv` requests?

**Comment by hainm** [comment]
never mind. I managed to have pytraj works with `mdsrv` now.

**Comment by arose** [comment]
oh, sorry missed seeing this one

> In this line, does that mean trajectory file is open every time mdsrv requests?

no, it is cached

**Comment by hainm** [comment]
thanks.

I have one more question. I already made `mdsrv` works with `pytraj` and this is for AMBER user (or for anyone using `pytraj`).

To avoid confusion with your branch, should I rename `mdsrv` in my fork to `mdsrv2` or something else? or may be rename as `nglview-server`? :D

**Comment by hainm** [comment]
But I only wants AMBER users to use `mdsrv` in their local machine, just like `vmd` or `pymol`. So using `server` or `srv` might be very confusing.

**Comment by arose** [comment]
Couldn't the use of pytraj instead of of simpletraj just be a config option?

**Comment by hainm** [comment]
a yes, you're right.
